### ISSUE TITLE
What parameters can I use to limit the number and number of sub-questions?

### ISSUE THREAD

**Issue by JPHu3312** [zilliztech/deep-searcher#163]
I just want to know, how can I use follow parameters to limit the sub-queries?

```
query_settings:
  max_iter: 5

load_settings:
  chunk_size: 1500
  chunk_overlap: 100
```

And what limits the number of sub-questions each time, is it automatically generated by LLM?
The max_iter is the maximum number of rotations, beyond this number, will the results be summarized directly?

Could you please provide a detailed parameter description so that I can customize the configuration?
